<template>
   <div class="bg-gray-900">
       <div class="max-w-screen-md px-4 md:px-8 mx-auto">
           <h1 class="text-white text-2xl sm:text-3xl font-bold text-center mb-4 md:mb-6">Company information</h1>
           <p class="text-gray-400 sm:text-lg mb-6 md:mb-8">
               Welcome to Hypefox Studios, we thrive on providing valuable services to both businesses and consumers. Our team is dedicated to delivering the highest quality solutions, ensuring our clients achieve their goals and meet their needs. In addition to our professional services, we also create entertaining game servers for players to enjoy. We believe in the importance of reliability and security, and our team works tirelessly to ensure our services and products meet the highest standards.
           </p>
           <h2 class="text-white text-xl sm:text-2xl font-semibold mb-2 md:mb-4">About us</h2>
           <p class="text-gray-400 sm:text-lg mb-6 md:mb-8">Hypefox Studios was founded as Hypefox Studios LTD on October 17, 2022, by Emilio P. from Sweden and co-founded by Lazar S. from Romania, who serves as the chief marketing officer. Our company provides exceptional services to both businesses and consumers, ensuring that our clients receive the best possible solutions to meet their needs. Our team is made up of experienced professionals who are dedicated to providing high-quality services and products that exceed our clients' expectations.<br><br>At Hypefox Studios, we are passionate about creating innovative game servers that offer a unique and immersive experience for our players. Our team is constantly exploring new and exciting ideas to push the boundaries of what is possible in the gaming industry.<br><br>We place a strong emphasis on reliability and security, ensuring that our clients can trust us to deliver exceptional service and products. Our goal is to become a leader in our industry, providing the highest quality solutions and services to our clients. Join us on our journey towards excellence and experience the difference that Hypefox Studios can make for your business or gaming needs.</p>
           <blockquote class="text-gray-400 sm:text-lg italic border-l-4 pl-4 md:pl-6 mb-6 md:mb-8">"Creating meaningful and valuable experiences for our clients and players is at the core of what we do. We strive to exceed expectations and deliver excellence in everything we do." - Emilio P., Founder of Hypefox Studios.</blockquote>
           <h2 class="text-white text-xl sm:text-2xl font-semibold mb-2 md:mb-4">Investor relations</h2>
           <p class="text-gray-400 sm:text-lg">At Hypefox Studios, we appreciate the interest and support of our community and potential investors. However, at this time, we are not accepting any outside investments. We are a private limited company and are focused on building and expanding our business with the resources currently available to us.<br><br>While we appreciate the confidence in our company and its potential for growth, we are committed to maintaining our independence and ensuring that we can pursue our vision for the future in the most effective and efficient way possible.<br><br>Thank you for your interest in Hypefox Studios. We remain dedicated to delivering outstanding services and experiences for our clients and players, and we look forward to continuing to grow and evolve in the years ahead.</p>
       </div>
   </div>
</template>
